// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChquMlnQC3-Qz6M0Kw1-To3oN4EibU3LY',
    appId: '1:541125435227:web:7f186202c835fd3775447e',
    messagingSenderId: '541125435227',
    projectId: 'travel-app-axrxlo',
    authDomain: 'travel-app-axrxlo.firebaseapp.com',
    storageBucket: 'travel-app-axrxlo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ95i9rhxF6sOC2tBn9WXfQLXw55cB4t0',
    appId: '1:541125435227:android:78fa097a65bf8b3775447e',
    messagingSenderId: '541125435227',
    projectId: 'travel-app-axrxlo',
    storageBucket: 'travel-app-axrxlo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFdqOzouIcpZ204yE-j7uFjHMlPs9r4e4',
    appId: '1:541125435227:ios:3ef68f91da3a11bf75447e',
    messagingSenderId: '541125435227',
    projectId: 'travel-app-axrxlo',
    storageBucket: 'travel-app-axrxlo.firebasestorage.app',
    iosBundleId: 'com.mycompany.travelapp.healthapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFdqOzouIcpZ204yE-j7uFjHMlPs9r4e4',
    appId: '1:541125435227:ios:3ef68f91da3a11bf75447e',
    messagingSenderId: '541125435227',
    projectId: 'travel-app-axrxlo',
    storageBucket: 'travel-app-axrxlo.firebasestorage.app',
    iosBundleId: 'com.mycompany.travelapp.healthapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChquMlnQC3-Qz6M0Kw1-To3oN4EibU3LY',
    appId: '1:541125435227:web:a5cdc91e9bfdf35e75447e',
    messagingSenderId: '541125435227',
    projectId: 'travel-app-axrxlo',
    authDomain: 'travel-app-axrxlo.firebaseapp.com',
    storageBucket: 'travel-app-axrxlo.firebasestorage.app',
  );
}
